In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("mabel.txt",header=None, on_bad_lines='skip', encoding='utf8')

In [4]:
df

           0                                                  1
0   05/12/19   1:42 pm - Messages to this chat and calls are...
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [6]:
df= df.drop(0)

In [7]:
df

           0                                                  1
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [8]:
df.columns = ['Date', 'chat'] # Replacing 0 and 1 to Date and Chat

In [9]:
df.columns

Index(['Date', 'chat'], dtype='object')

In [10]:
df

        Date                                               chat
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [11]:
Message = df["chat"].str.split("-",n=1,expand=True)

In [12]:
Message #time and name splited

             0                                                  1
1     1:42 pm     Mabel Infoziant: Hi this is Mabel we just spoke
2     1:42 pm              Mabel Infoziant: What’s your full name
3     1:42 pm                                 AR❤: Ramisha Rani K
4     1:42 pm                                 Mabel Infoziant: Ok
5     1:42 pm             Mabel Infoziant: ramisharanik@gmail.com
6     1:43 pm                     Mabel Infoziant: Your email Id?
7     1:43 pm                                        AR❤: Yes Mam
8     1:43 pm    Mabel Infoziant: I will send 2 abstracts for ...
9     1:43 pm                                       AR❤: Yeah mam
10    1:43 pm    Mabel Infoziant: Give me the list that u have...
11    1:43 pm    Mabel Infoziant: Send me cbe office address a...
12    1:44 pm    AR❤: Yeah Mam within Evening I will forward y...
13    1:45 pm    AR❤: Tomorrow I have to visit the office.yet ...
14    1:48 pm                                 Mabel Infoziant: ok
15    1:48 pm    Mabel Infoziant: send the details of office l...
16    1:49 pm    AR❤: Sure mam. Soon I will share details with...
17    2:00 pm    AR❤: I have read the Abstract mam. We can do ...
18    2:04 pm    Mabel Infoziant: I think Vignesh has the data...
19    2:04 pm          Mabel Infoziant: I have sent the abstracts
20    2:06 pm                                         AR❤: Ok mam
21    2:07 pm    AR❤: I have read both the abstract mam. We ca...
22    4:44 pm    Mabel Infoziant: Yes we need to ya about amou...
23    4:48 pm                                      AR❤: Sure mam.
24    8:07 pm                              AR❤: Shall I call mam?
25   10:45 pm    Mabel Infoziant: Hi I was at church couldn’t ...
26   11:52 pm                                     AR❤: It's k mam
27   11:55 pm    AR❤: Just to know the tomorrow plan mam.will ...
28   12:09 pm                AR❤: Mam can u send Vignesh number??
29   12:13 pm    Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...
30   12:23 pm           Mabel Infoziant: I was in a meeting sorry
31   12:25 pm                                AR❤: Can I cal u mam
32   12:26 pm    AR❤: Waiting for u r finalization of rates fo...
33   12:26 pm    AR❤: If we finiliaze I can work with full inv...
34   12:28 pm    AR❤: So what ever may be ..if you think your ...
35   12:28 pm                       AR❤: You deleted this message
36   12:29 pm                                 AR❤: Do the needful
37   12:41 pm    Mabel Infoziant: No ma please hold I am in a ...
38   12:42 pm                                 AR❤: Ok mam thank u
39    7:59 am    Mabel Infoziant: Ramisha we need to talk toda...
40    8:00 am    Mabel Infoziant: Be ready to discuss about th...
41    8:55 am                                       AR❤: Okay mam
42    2:26 pm                                 Mabel Infoziant: ok
43    8:22 pm                                AR❤: Mam are u free?
44    8:40 pm    Mabel Infoziant: Am at church can call very l...
45    8:40 pm    AR❤: Kk mam. I will ask Arun brother. Small d...
46    3:09 pm                                         AR❤: Hi mam
47    3:09 pm                               AR❤: Any updates mam?
48    3:11 pm    Mabel Infoziant: U might have to start on the...
49    3:11 pm    Mabel Infoziant: There is one project that go...
50    3:12 pm                                       AR❤: Kk mam👍🏻

In [15]:
df['Time']=Message[0]

In [16]:
df

        Date                                               chat        Time
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...    1:42 pm
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name    1:42 pm
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K    1:42 pm
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok    1:42 pm
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...    1:42 pm
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?    1:43 pm
7   05/12/19                             1:43 pm - AR❤: Yes Mam    1:43 pm
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...    1:43 pm
9   05/12/19                            1:43 pm - AR❤: Yeah mam    1:43 pm
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...    1:43 pm
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...    1:43 pm
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...    1:44 pm
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...    1:45 pm
14  05/12/19                      1:48 pm - Mabel Infoziant: ok    1:48 pm
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...    1:48 pm
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...    1:49 pm
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...    2:00 pm
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...    2:04 pm
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...    2:04 pm
20  05/12/19                              2:06 pm - AR❤: Ok mam    2:06 pm
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...    2:07 pm
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...    4:44 pm
23  05/12/19                           4:48 pm - AR❤: Sure mam.    4:48 pm
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?    8:07 pm
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...   10:45 pm
26  08/12/19                         11:52 pm - AR❤: It's k mam   11:52 pm
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...   11:55 pm
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??   12:09 pm
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...   12:13 pm
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...   12:23 pm
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam   12:25 pm
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...   12:26 pm
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...   12:26 pm
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...   12:28 pm
35  09/12/19           12:28 pm - AR❤: You deleted this message   12:28 pm
36  09/12/19                     12:29 pm - AR❤: Do the needful   12:29 pm
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...   12:41 pm
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u   12:42 pm
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...    7:59 am
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...    8:00 am
41  10/12/19                            8:55 am - AR❤: Okay mam    8:55 am
42  12/12/19                      2:26 pm - Mabel Infoziant: ok    2:26 pm
43  15/12/19                     8:22 pm - AR❤: Mam are u free?    8:22 pm
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...    8:40 pm
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...    8:40 pm
46  18/12/19                              3:09 pm - AR❤: Hi mam    3:09 pm
47  18/12/19                    3:09 pm - AR❤: Any updates mam?    3:09 pm
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...    3:11 pm
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...    3:11 pm
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻    3:12 pm

In [17]:
Message1=Message[1].str.split(":",n=1,expand=True) #Message column 1 data we splittting the : in chat name seprate)

In [18]:
Message1

                   0                                                  1
1    Mabel Infoziant                     Hi this is Mabel we just spoke
2    Mabel Infoziant                              What’s your full name
3                AR❤                                     Ramisha Rani K
4    Mabel Infoziant                                                 Ok
5    Mabel Infoziant                             ramisharanik@gmail.com
6    Mabel Infoziant                                     Your email Id?
7                AR❤                                            Yes Mam
8    Mabel Infoziant     I will send 2 abstracts for u to start working
9                AR❤                                           Yeah mam
10   Mabel Infoziant                   Give me the list that u have too
11   Mabel Infoziant   Send me cbe office address and phone number I...
12               AR❤    Yeah Mam within Evening I will forward you mam.
13               AR❤   Tomorrow I have to visit the office.yet not I...
14   Mabel Infoziant                                                 ok
15   Mabel Infoziant   send the details of office location once u ge...
16               AR❤   Sure mam. Soon I will share details with you mam
17               AR❤   I have read the Abstract mam. We can do mam. ...
18   Mabel Infoziant   I think Vignesh has the data set will ask him...
19   Mabel Infoziant                          I have sent the abstracts
20               AR❤                                             Ok mam
21               AR❤   I have read both the abstract mam. We can do ...
22   Mabel Infoziant   Yes we need to ya about amount and all other ...
23               AR❤                                          Sure mam.
24               AR❤                                  Shall I call mam?
25   Mabel Infoziant         Hi I was at church couldn’t take your call
26               AR❤                                         It's k mam
27               AR❤   Just to know the tomorrow plan mam.will see t...
28               AR❤                    Mam can u send Vignesh number??
29   Mabel Infoziant           Vignesh ML Infoziant.vcf (file attached)
30   Mabel Infoziant                           I was in a meeting sorry
31               AR❤                                    Can I cal u mam
32               AR❤   Waiting for u r finalization of rates for our...
33               AR❤   If we finiliaze I can work with full involvem...
34               AR❤   So what ever may be ..if you think your are c...
35               AR❤                           You deleted this message
36               AR❤                                     Do the needful
37   Mabel Infoziant   No ma please hold I am in a hot meeting with ...
38               AR❤                                     Ok mam thank u
39   Mabel Infoziant   Ramisha we need to talk today i will call u a...
40   Mabel Infoziant     Be ready to discuss about the ML titles u have
41               AR❤                                           Okay mam
42   Mabel Infoziant                                                 ok
43               AR❤                                    Mam are u free?
44   Mabel Infoziant   Am at church can call very late or tomorrow only
45               AR❤   Kk mam. I will ask Arun brother. Small doubt ...
46               AR❤                                             Hi mam
47               AR❤                                   Any updates mam?
48   Mabel Infoziant     U might have to start on the WhatsApp analysis
49   Mabel Infoziant            There is one project that got committed
50               AR❤                                           Kk mam👍🏻

In [19]:
df["Name"]=Message1[0]   #Adding the Time on the DF

In [20]:
df

,Date,chat,Time,Name
1,05/12/19,1:42 pm - Mabel Infoziant: Hi this is Mabel w...,1:42 pm,Mabel Infoziant
2,05/12/19,1:42 pm - Mabel Infoziant: What’s your full name,1:42 pm,Mabel Infoziant
3,05/12/19,1:42 pm - AR❤: Ramisha Rani K,1:42 pm,AR❤
4,05/12/19,1:42 pm - Mabel Infoziant: Ok,1:42 pm,Mabel Infoziant
5,05/12/19,1:42 pm - Mabel Infoziant: ramisharanik@gmail...,1:42 pm,Mabel Infoziant
6,05/12/19,1:43 pm - Mabel Infoziant: Your email Id?,1:43 pm,Mabel Infoziant
7,05/12/19,1:43 pm - AR❤: Yes Mam,1:43 pm,AR❤
8,05/12/19,1:43 pm - Mabel Infoziant: I will send 2 abst...,1:43 pm,Mabel Infoziant
9,05/12/19,1:43 pm - AR❤: Yeah mam,1:43 pm,AR❤
10,05/12/19,1:43 pm - Mabel Infoziant: Give me the list t...,1:43 pm,Mabel Infoziant
11,05/12/19,1:43 pm - Mabel Infoziant: Send me cbe office...,1:43 pm,Mabel Infoziant
12,05/12/19,1:44 pm - AR❤: Yeah Mam within Evening I will...,1:44 pm,AR❤
13,05/12/19,1:45 pm - AR❤: Tomorrow I have to visit the o...,1:45 pm,AR❤
14,05/12/19,1:48 pm - Mabel Infoziant: ok,1:48 pm,Mabel Infoziant
15,05/12/19,1:48 pm - Mabel Infoziant: send the details o...,1:48 pm,Mabel Infoziant
16,05/12/19,1:49 pm - AR❤: Sure mam. Soon I will share de...,1:49 pm,AR❤
17,05/12/19,2:00 pm - AR❤: I have read the Abstract mam. ...,2:00 pm,AR❤
18,05/12/19,2:04 pm - Mabel Infoziant: I think Vignesh ha...,2:04 pm,Mabel Infoziant
19,05/12/19,2:04 pm - Mabel Infoziant: I have sent the ab...,2:04 pm,Mabel Infoziant
20,05/12/19,2:06 pm - AR❤: Ok mam,2:06 pm,AR❤
21,05/12/19,2:07 pm - AR❤: I have read both the abstract ...,2:07 pm,AR❤
22,05/12/19,4:44 pm - Mabel Infoziant: Yes we need to ya ...,4:44 pm,Mabel Infoziant
23,05/12/19,4:48 pm - AR❤: Sure mam.,4:48 pm,AR❤
24,05/12/19,8:07 pm - AR❤: Shall I call mam?,8:07 pm,AR❤
25,08/12/19,10:45 pm - Mabel Infoziant: Hi I was at churc...,10:45 pm,Mabel Infoziant
26,08/12/19,11:52 pm - AR❤: It's k mam,11:52 pm,AR❤
27,08/12/19,11:55 pm - AR❤: Just to know the tomorrow pla...,11:55 pm,AR❤
28,09/12/19,12:09 pm - AR❤: Mam can u send Vignesh number??,12:09 pm,AR❤
29,09/12/19,12:13 pm - Mabel Infoziant: Vignesh ML Infozi...,12:13 pm,Mabel Infoziant
30,09/12/19,12:23 pm - Mabel Infoziant: I was in a meetin...,12:23 pm,Mabel Infoziant
31,09/12/19,12:25 pm - AR❤: Can I cal u mam,12:25 pm,AR❤
32,09/12/19,12:26 pm - AR❤: Waiting for u r finalization ...,12:26 pm,AR❤
33,09/12/19,12:26 pm - AR❤: If we finiliaze I can work wi...,12:26 pm,AR❤
34,09/12/19,12:28 pm - AR❤: So what ever may be ..if you ...,12:28 pm,AR❤
35,09/12/19,12:28 pm - AR❤: You deleted this message,12:28 pm,AR❤
36,09/12/19,12:29 pm - AR❤: Do the needful,12:29 pm,AR❤
37,09/12/19,12:41 pm - Mabel Infoziant: No ma please hold...,12:41 pm,Mabel Infoziant
38,09/12/19,12:42 pm - AR❤: Ok mam thank u,12:42 pm,AR❤
39,10/12/19,7:59 am - Mabel Infoziant: Ramisha we need to...,7:59 am,Mabel Infoziant
40,10/12/19,8:00 am - Mabel Infoziant: Be ready to discus...,8:00 am,Mabel Infoziant
41,10/12/19,8:55 am - AR❤: Okay mam,8:55 am,AR❤
42,12/12/19,2:26 pm - Mabel Infoziant: ok,2:26 pm,Mabel Infoziant
43,15/12/19,8:22 pm - AR❤: Mam are u free?,8:22 pm,AR❤
44,15/12/19,8:40 pm - Mabel Infoziant: Am at church can c...,8:40 pm,Mabel Infoziant
45,15/12/19,8:40 pm - AR❤: Kk mam. I will ask Arun brothe...,8:40 pm,AR❤
46,18/12/19,3:09 pm - AR❤: Hi mam,3:09 pm,AR❤
47,18/12/19,3:09 pm - AR❤: Any updates mam?,3:09 pm,AR❤
48,18/12/19,3:11 pm - Mabel Infoziant: U might have to st...,3:11 pm,Mabel Infoziant
49,18/12/19,3:11 pm - Mabel Infoziant: There is one proje...,3:11 pm,Mabel Infoziant
50,18/12/19,3:12 pm - AR❤: Kk mam👍🏻,3:12 pm,AR❤

In [22]:
#Re-arranging the Column
df=df[["Date", "Time", "Name", "chat"]]

In [23]:
df

,Date,Time,Name,chat
1,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: What’s your full name
3,05/12/19,1:42 pm,AR❤,1:42 pm - AR❤: Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: Ok
5,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Your email Id?
7,05/12/19,1:43 pm,AR❤,1:43 pm - AR❤: Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: I will send 2 abst...
9,05/12/19,1:43 pm,AR❤,1:43 pm - AR❤: Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Give me the list t...
11,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Send me cbe office...
12,05/12/19,1:44 pm,AR❤,1:44 pm - AR❤: Yeah Mam within Evening I will...
13,05/12/19,1:45 pm,AR❤,1:45 pm - AR❤: Tomorrow I have to visit the o...
14,05/12/19,1:48 pm,Mabel Infoziant,1:48 pm - Mabel Infoziant: ok
15,05/12/19,1:48 pm,Mabel Infoziant,1:48 pm - Mabel Infoziant: send the details o...
16,05/12/19,1:49 pm,AR❤,1:49 pm - AR❤: Sure mam. Soon I will share de...
17,05/12/19,2:00 pm,AR❤,2:00 pm - AR❤: I have read the Abstract mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,2:04 pm - Mabel Infoziant: I think Vignesh ha...
19,05/12/19,2:04 pm,Mabel Infoziant,2:04 pm - Mabel Infoziant: I have sent the ab...
20,05/12/19,2:06 pm,AR❤,2:06 pm - AR❤: Ok mam
21,05/12/19,2:07 pm,AR❤,2:07 pm - AR❤: I have read both the abstract ...
22,05/12/19,4:44 pm,Mabel Infoziant,4:44 pm - Mabel Infoziant: Yes we need to ya ...
23,05/12/19,4:48 pm,AR❤,4:48 pm - AR❤: Sure mam.
24,05/12/19,8:07 pm,AR❤,8:07 pm - AR❤: Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,10:45 pm - Mabel Infoziant: Hi I was at churc...
26,08/12/19,11:52 pm,AR❤,11:52 pm - AR❤: It's k mam
27,08/12/19,11:55 pm,AR❤,11:55 pm - AR❤: Just to know the tomorrow pla...
28,09/12/19,12:09 pm,AR❤,12:09 pm - AR❤: Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30,09/12/19,12:23 pm,Mabel Infoziant,12:23 pm - Mabel Infoziant: I was in a meetin...
31,09/12/19,12:25 pm,AR❤,12:25 pm - AR❤: Can I cal u mam
32,09/12/19,12:26 pm,AR❤,12:26 pm - AR❤: Waiting for u r finalization ...
33,09/12/19,12:26 pm,AR❤,12:26 pm - AR❤: If we finiliaze I can work wi...
34,09/12/19,12:28 pm,AR❤,12:28 pm - AR❤: So what ever may be ..if you ...
35,09/12/19,12:28 pm,AR❤,12:28 pm - AR❤: You deleted this message
36,09/12/19,12:29 pm,AR❤,12:29 pm - AR❤: Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,12:41 pm - Mabel Infoziant: No ma please hold...
38,09/12/19,12:42 pm,AR❤,12:42 pm - AR❤: Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,7:59 am - Mabel Infoziant: Ramisha we need to...
40,10/12/19,8:00 am,Mabel Infoziant,8:00 am - Mabel Infoziant: Be ready to discus...
41,10/12/19,8:55 am,AR❤,8:55 am - AR❤: Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,2:26 pm - Mabel Infoziant: ok
43,15/12/19,8:22 pm,AR❤,8:22 pm - AR❤: Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,8:40 pm - Mabel Infoziant: Am at church can c...
45,15/12/19,8:40 pm,AR❤,8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46,18/12/19,3:09 pm,AR❤,3:09 pm - AR❤: Hi mam
47,18/12/19,3:09 pm,AR❤,3:09 pm - AR❤: Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,3:11 pm - Mabel Infoziant: U might have to st...
49,18/12/19,3:11 pm,Mabel Infoziant,3:11 pm - Mabel Infoziant: There is one proje...
50,18/12/19,3:12 pm,AR❤,3:12 pm - AR❤: Kk mam👍🏻

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Time    50 non-null     object
 2   Name    50 non-null     object
 3   chat    50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB

# Perform Sentiment Analysis

In [25]:
# for Sentiment analysis no need of preprocessing since it is already build

In [27]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.10.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: defusedxml in c:\users\lenovo\anaconda3\envs\ml\lib\site-packages (from nltk) (0.7.1)
Collecting click (from nltk)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in c:\users\lenovo\anaconda3\envs\ml\lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.7.19-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\envs\ml\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.10.2-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 1.5 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.7 MB 1.5 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 1.7 MB/s  0:00:01
Downloading regex-2026.7.19-cp311-cp311-win_amd64.whl (277 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading tqdm-4.70.0-py3-none-any.whl (80 kB)
Installing collected packages: tqdm, regex, click, nltk

   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------- ----------------------------- 1/4 [regex]
   ---------- ----------------------------- 1/4 [regex]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ---------------------------------------- 4/4 [nltk]

Successfully installed click-8.4.2 nltk-3.10.2 regex-2026.7.19 tqdm-4.70.0

In [28]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [29]:
dataset=df

In [30]:
dataset.dropna(inplace=True)

In [35]:
sid=SentimentIntensityAnalyzer()

In [36]:
senti=sid.polarity_scores(dataset['chat'][4])

In [37]:
senti

{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'compound': 0.296}

In [38]:
senti['compound']

0.296

In [42]:
def sentimentalAnalysis(data,columnname):
       #downloading vader_lexicon for the process
        import matplotlib.pyplot as plt
        import seaborn as sns
        "Importing Necessary Packeage"
        from nltk.sentiment.vader import SentimentIntensityAnalyzer
        sid = SentimentIntensityAnalyzer()
        
        "Deleting null pr empty value"
        data.dropna(inplace=True)
        
        "Checking for a comment"
        #sid.polarity_scores(data[columnname][93])
        
        "Creating respective columns"
        
        data['scores'] = data[columnname].apply(lambda commentText: sid.polarity_scores(commentText))
        data['compound']  = data['scores'].apply(lambda score_dict: score_dict['compound'])
        data['Negative']  = data['scores'].apply(lambda score_dict: score_dict['neg'])
        data['Postive']  = data['scores'].apply(lambda score_dict: score_dict['pos'])
        data['Neutral']  = data['scores'].apply(lambda score_dict: score_dict['neu'])
        
        "Creating final pos or neg using compound score"
        data['comp_score'] = data['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
        plt.clf()
        #comp=sns.countplot(x = 'comp_score', hue = 'Name', data = data, palette = 'magma')
        #comp.figure.savefig("date_charts.png")
        "Checking how many pos and neg"
        posneg=pd.DataFrame(data['comp_score'].value_counts())
        return posneg,data

In [44]:
pos,data_Senti=sentimentalAnalysis(dataset,columnname='chat') #already inbuily function just give columnname

In [45]:
data_Senti

,Date,Time,Name,chat,scores,compound,Negative,Postive,Neutral,comp_score
1,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: Hi this is Mabel w...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
2,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
3,05/12/19,1:42 pm,AR❤,1:42 pm - AR❤: Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
4,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: Ok,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos
5,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: ramisharanik@gmail...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
6,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
7,05/12/19,1:43 pm,AR❤,1:43 pm - AR❤: Yes Mam,"{'neg': 0.0, 'neu': 0.597, 'pos': 0.403, 'comp...",0.4019,0.000,0.403,0.597,pos
8,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: I will send 2 abst...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
9,05/12/19,1:43 pm,AR❤,1:43 pm - AR❤: Yeah mam,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos
10,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Give me the list t...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
11,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Send me cbe office...,"{'neg': 0.0, 'neu': 0.933, 'pos': 0.067, 'comp...",0.0772,0.000,0.067,0.933,pos
12,05/12/19,1:44 pm,AR❤,1:44 pm - AR❤: Yeah Mam within Evening I will...,"{'neg': 0.0, 'neu': 0.82, 'pos': 0.18, 'compou...",0.2960,0.000,0.180,0.820,pos
13,05/12/19,1:45 pm,AR❤,1:45 pm - AR❤: Tomorrow I have to visit the o...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
14,05/12/19,1:48 pm,Mabel Infoziant,1:48 pm - Mabel Infoziant: ok,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos
15,05/12/19,1:48 pm,Mabel Infoziant,1:48 pm - Mabel Infoziant: send the details o...,"{'neg': 0.0, 'neu': 0.907, 'pos': 0.093, 'comp...",0.3612,0.000,0.093,0.907,pos
16,05/12/19,1:49 pm,AR❤,1:49 pm - AR❤: Sure mam. Soon I will share de...,"{'neg': 0.0, 'neu': 0.69, 'pos': 0.31, 'compou...",0.5423,0.000,0.310,0.690,pos
17,05/12/19,2:00 pm,AR❤,2:00 pm - AR❤: I have read the Abstract mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
18,05/12/19,2:04 pm,Mabel Infoziant,2:04 pm - Mabel Infoziant: I think Vignesh ha...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
19,05/12/19,2:04 pm,Mabel Infoziant,2:04 pm - Mabel Infoziant: I have sent the ab...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
20,05/12/19,2:06 pm,AR❤,2:06 pm - AR❤: Ok mam,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos
21,05/12/19,2:07 pm,AR❤,2:07 pm - AR❤: I have read both the abstract ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
22,05/12/19,4:44 pm,Mabel Infoziant,4:44 pm - Mabel Infoziant: Yes we need to ya ...,"{'neg': 0.0, 'neu': 0.87, 'pos': 0.13, 'compou...",0.4019,0.000,0.130,0.870,pos
23,05/12/19,4:48 pm,AR❤,4:48 pm - AR❤: Sure mam.,"{'neg': 0.0, 'neu': 0.635, 'pos': 0.365, 'comp...",0.3182,0.000,0.365,0.635,pos
24,05/12/19,8:07 pm,AR❤,8:07 pm - AR❤: Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
25,08/12/19,10:45 pm,Mabel Infoziant,10:45 pm - Mabel Infoziant: Hi I was at churc...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
26,08/12/19,11:52 pm,AR❤,11:52 pm - AR❤: It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
27,08/12/19,11:55 pm,AR❤,11:55 pm - AR❤: Just to know the tomorrow pla...,"{'neg': 0.0, 'neu': 0.818, 'pos': 0.182, 'comp...",0.4404,0.000,0.182,0.818,pos
28,09/12/19,12:09 pm,AR❤,12:09 pm - AR❤: Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.808, 'pos': 0.192, 'comp...",0.1680,0.000,0.192,0.808,pos
29,09/12/19,12:13 pm,Mabel Infoziant,12:13 pm - Mabel Infoziant: Vignesh ML Infozi...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
30,09/12/19,12:23 pm,Mabel Infoziant,12:23 pm - Mabel Infoziant: I was in a meetin...,"{'neg': 0.157, 'neu': 0.843, 'pos': 0.0, 'comp...",-0.0772,0.157,0.000,0.843,neg
31,09/12/19,12:25 pm,AR❤,12:25 pm - AR❤: Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
32,09/12/19,12:26 pm,AR❤,12:26 pm - AR❤: Waiting for u r finalization ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
33,09/12/19,12:26 pm,AR❤,12:26 pm - AR❤: If we finiliaze I can work wi...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
34,09/12/19,12:28 pm,AR❤,12:28 pm - AR❤: So what ever may be ..if you ...,"{'neg': 0.0, 'neu': 0.887, 'pos': 0.113, 'comp...",0.5106,0.000,0.113,0.887,pos
35,09/12/19,12:28 pm,AR❤,12:28 pm - AR❤: You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
36,09/12/19,12:29 pm,AR❤,12:29 pm - AR❤: Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
37,09/12/19,12:41 pm,Mabel Infoziant,12:41 pm - Mabel Infoziant: No ma please hold...,"{'neg': 0.151, 'neu': 0.772, 'pos': 0.077, 'co...",-0.2960,0.151,0.077,0.772,neg
38,09/12/19,12:42 pm,AR❤,12:42 pm - AR❤: Ok mam thank u,"{'neg': 0.0, 'neu': 0.46, 'pos': 0.54, 'compou...",0.5719,0.000,0.540,0.460,pos
39,10/12/19,7:59 am,Mabel Infoziant,7:59 am - Mabel Infoziant: Ramisha we need to...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
40,10/12/19,8:00 am,Mabel Infoziant,8:00 am - Mabel Infoziant: Be ready to discus...,"{'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'comp...",0.3612,0.000,0.172,0.828,pos
41,10/12/19,8:55 am,AR❤,8:55 am - AR❤: Okay mam,"{'neg': 0.0, 'neu': 0.678, 'pos': 0.322, 'comp...",0.2263,0.000,0.322,0.678,pos
42,12/12/19,2:26 pm,Mabel Infoziant,2:26 pm - Mabel Infoziant: ok,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos
43,15/12/19,8:22 pm,AR❤,8:22 pm - AR❤: Mam are u free?,"{'neg': 0.0, 'neu': 0.602, 'pos': 0.398, 'comp...",0.5106,0.000,0.398,0.602,pos
44,15/12/19,8:40 pm,Mabel Infoziant,8:40 pm - Mabel Infoziant: Am at church can c...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
45,15/12/19,8:40 pm,AR❤,8:40 pm - AR❤: Kk mam. I will ask Arun brothe...,"{'neg': 0.098, 'neu': 0.664, 'pos': 0.238, 'co...",0.5574,0.098,0.238,0.664,pos
46,18/12/19,3:09 pm,AR❤,3:09 pm - AR❤: Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
47,18/12/19,3:09 pm,AR❤,3:09 pm - AR❤: Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
48,18/12/19,3:11 pm,Mabel Infoziant,3:11 pm - Mabel Infoziant: U might have to st...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
49,18/12/19,3:11 pm,Mabel Infoziant,3:11 pm - Mabel Infoziant: There is one proje...,"{'neg': 0.0, 'neu': 0.826, 'pos': 0.174, 'comp...",0.2732,0.000,0.174,0.826,pos
50,18/12/19,3:12 pm,AR❤,3:12 pm - AR❤: Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.615, 'pos': 0.385, 'comp...",0.3612,0.000,0.385,0.615,pos

In [46]:
pos

            count
comp_score
pos            48
neg             2

# Topic Modelling

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
tfidf=TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')      # vector created  TEXT TO NUMBER
dtm=tfidf.fit_transform(df["chat"])

In [50]:
from sklearn.decomposition import NMF               #NON MATRIX FACTORIZATION ALGM
nmf_model=NMF(n_components=5,random_state=42)    #5 topics need
nmf_model.fit(dtm)

NMF(n_components=5, random_state=42)

In [51]:
# Retrieve the top words for each topic
for index, topic in enumerate(nmf_model.components_):
    # Use get_feature_names_out() to retrieve feature names
    results = [tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]]
    print(f"Topic {index + 1}: {', '.join(results)}")

Topic 1: kk, sure, read, abstract, yeah, 07, 09, pm, ar, mam
Topic 2: details, need, 04, ml, abstracts, send, pm, 43, mabel, infoziant
Topic 3: think, vignesh, kk, meeting, finiliaze, 28, pm, 26, ar, 12
Topic 4: 26, just, 48, hi, ramisha, pm, infoziant, mabel, ok, 42
Topic 5: infoziant, know, mabel, just, 55, pm, start, project, tomorrow, 11

In [52]:
print("Shape of DTM:", dtm.shape)
print("Feature names:", tfidf.get_feature_names_out())

Shape of DTM: (50, 52)
Feature names: ['00' '04' '07' '09' '10' '11' '12' '26' '28' '40' '42' '43' '44' '45'
 '48' '55' 'abstract' 'abstracts' 'ar' 'ask' 'church' 'details'
 'finiliaze' 'hi' 'infoziant' 'just' 'kk' 'know' 'mabel' 'mam' 'meeting'
 'ml' 'need' 'number' 'office' 'ok' 'phone' 'pm' 'project' 'ramisha'
 'read' 'send' 'share' 'soon' 'start' 'students' 'sure' 'think' 'tomorrow'
 'vignesh' 'yeah' 'yes']

In [53]:
topic_results=nmf_model.transform(dtm)
df["Topic"]=topic_results.argmax(axis=1)

In [54]:
df

,Date,Time,Name,chat,scores,compound,Negative,Postive,Neutral,comp_score,Topic
1,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: Hi this is Mabel w...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
2,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
3,05/12/19,1:42 pm,AR❤,1:42 pm - AR❤: Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
4,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: Ok,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos,3
5,05/12/19,1:42 pm,Mabel Infoziant,1:42 pm - Mabel Infoziant: ramisharanik@gmail...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
6,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
7,05/12/19,1:43 pm,AR❤,1:43 pm - AR❤: Yes Mam,"{'neg': 0.0, 'neu': 0.597, 'pos': 0.403, 'comp...",0.4019,0.000,0.403,0.597,pos,1
8,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: I will send 2 abst...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
9,05/12/19,1:43 pm,AR❤,1:43 pm - AR❤: Yeah mam,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos,0
10,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Give me the list t...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
11,05/12/19,1:43 pm,Mabel Infoziant,1:43 pm - Mabel Infoziant: Send me cbe office...,"{'neg': 0.0, 'neu': 0.933, 'pos': 0.067, 'comp...",0.0772,0.000,0.067,0.933,pos,1
12,05/12/19,1:44 pm,AR❤,1:44 pm - AR❤: Yeah Mam within Evening I will...,"{'neg': 0.0, 'neu': 0.82, 'pos': 0.18, 'compou...",0.2960,0.000,0.180,0.820,pos,0
13,05/12/19,1:45 pm,AR❤,1:45 pm - AR❤: Tomorrow I have to visit the o...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
14,05/12/19,1:48 pm,Mabel Infoziant,1:48 pm - Mabel Infoziant: ok,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos,3
15,05/12/19,1:48 pm,Mabel Infoziant,1:48 pm - Mabel Infoziant: send the details o...,"{'neg': 0.0, 'neu': 0.907, 'pos': 0.093, 'comp...",0.3612,0.000,0.093,0.907,pos,1
16,05/12/19,1:49 pm,AR❤,1:49 pm - AR❤: Sure mam. Soon I will share de...,"{'neg': 0.0, 'neu': 0.69, 'pos': 0.31, 'compou...",0.5423,0.000,0.310,0.690,pos,0
17,05/12/19,2:00 pm,AR❤,2:00 pm - AR❤: I have read the Abstract mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
18,05/12/19,2:04 pm,Mabel Infoziant,2:04 pm - Mabel Infoziant: I think Vignesh ha...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
19,05/12/19,2:04 pm,Mabel Infoziant,2:04 pm - Mabel Infoziant: I have sent the ab...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
20,05/12/19,2:06 pm,AR❤,2:06 pm - AR❤: Ok mam,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos,0
21,05/12/19,2:07 pm,AR❤,2:07 pm - AR❤: I have read both the abstract ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
22,05/12/19,4:44 pm,Mabel Infoziant,4:44 pm - Mabel Infoziant: Yes we need to ya ...,"{'neg': 0.0, 'neu': 0.87, 'pos': 0.13, 'compou...",0.4019,0.000,0.130,0.870,pos,1
23,05/12/19,4:48 pm,AR❤,4:48 pm - AR❤: Sure mam.,"{'neg': 0.0, 'neu': 0.635, 'pos': 0.365, 'comp...",0.3182,0.000,0.365,0.635,pos,0
24,05/12/19,8:07 pm,AR❤,8:07 pm - AR❤: Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
25,08/12/19,10:45 pm,Mabel Infoziant,10:45 pm - Mabel Infoziant: Hi I was at churc...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
26,08/12/19,11:52 pm,AR❤,11:52 pm - AR❤: It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
27,08/12/19,11:55 pm,AR❤,11:55 pm - AR❤: Just to know the tomorrow pla...,"{'neg': 0.0, 'neu': 0.818, 'pos': 0.182, 'comp...",0.4404,0.000,0.182,0.818,pos,4
28,09/12/19,12:09 pm,AR❤,12:09 pm - AR❤: Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.808, 'pos': 0.192, 'comp...",0.1680,0.000,0.192,0.808,pos,2
29,09/12/19,12:13 pm,Mabel Infoziant,12:13 pm - Mabel Infoziant: Vignesh ML Infozi...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
30,09/12/19,12:23 pm,Mabel Infoziant,12:23 pm - Mabel Infoziant: I was in a meetin...,"{'neg': 0.157, 'neu': 0.843, 'pos': 0.0, 'comp...",-0.0772,0.157,0.000,0.843,neg,2
31,09/12/19,12:25 pm,AR❤,12:25 pm - AR❤: Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
32,09/12/19,12:26 pm,AR❤,12:26 pm - AR❤: Waiting for u r finalization ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
33,09/12/19,12:26 pm,AR❤,12:26 pm - AR❤: If we finiliaze I can work wi...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
34,09/12/19,12:28 pm,AR❤,12:28 pm - AR❤: So what ever may be ..if you ...,"{'neg': 0.0, 'neu': 0.887, 'pos': 0.113, 'comp...",0.5106,0.000,0.113,0.887,pos,2
35,09/12/19,12:28 pm,AR❤,12:28 pm - AR❤: You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
36,09/12/19,12:29 pm,AR❤,12:29 pm - AR❤: Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
37,09/12/19,12:41 pm,Mabel Infoziant,12:41 pm - Mabel Infoziant: No ma please hold...,"{'neg': 0.151, 'neu': 0.772, 'pos': 0.077, 'co...",-0.2960,0.151,0.077,0.772,neg,2
38,09/12/19,12:42 pm,AR❤,12:42 pm - AR❤: Ok mam thank u,"{'neg': 0.0, 'neu': 0.46, 'pos': 0.54, 'compou...",0.5719,0.000,0.540,0.460,pos,3
39,10/12/19,7:59 am,Mabel Infoziant,7:59 am - Mabel Infoziant: Ramisha we need to...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
40,10/12/19,8:00 am,Mabel Infoziant,8:00 am - Mabel Infoziant: Be ready to discus...,"{'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'comp...",0.3612,0.000,0.172,0.828,pos,1
41,10/12/19,8:55 am,AR❤,8:55 am - AR❤: Okay mam,"{'neg': 0.0, 'neu': 0.678, 'pos': 0.322, 'comp...",0.2263,0.000,0.322,0.678,pos,0
42,12/12/19,2:26 pm,Mabel Infoziant,2:26 pm - Mabel Infoziant: ok,"{'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'comp...",0.2960,0.000,0.355,0.645,pos,3
43,15/12/19,8:22 pm,AR❤,8:22 pm - AR❤: Mam are u free?,"{'neg': 0.0, 'neu': 0.602, 'pos': 0.398, 'comp...",0.5106,0.000,0.398,0.602,pos,0
44,15/12/19,8:40 pm,Mabel Infoziant,8:40 pm - Mabel Infoziant: Am at church can c...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
45,15/12/19,8:40 pm,AR❤,8:40 pm - AR❤: Kk mam. I will ask Arun brothe...,"{'neg': 0.098, 'neu': 0.664, 'pos': 0.238, 'co...",0.5574,0.098,0.238,0.664,pos,0
46,18/12/19,3:09 pm,AR❤,3:09 pm - AR❤: Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
47,18/12/19,3:09 pm,AR❤,3:09 pm - AR❤: Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
48,18/12/19,3:11 pm,Mabel Infoziant,3:11 pm - Mabel Infoziant: U might have to st...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
49,18/12/19,3:11 pm,Mabel Infoziant,3:11 pm - Mabel Infoziant: There is one proje...,"{'neg': 0.0, 'neu': 0.826, 'pos': 0.174, 'comp...",0.2732,0.000,0.174,0.826,pos,4
50,18/12/19,3:12 pm,AR❤,3:12 pm - AR❤: Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.615, 'pos': 0.385, 'comp...",0.3612,0.000,0.385,0.615,pos,2

In [55]:
df["Topic"].value_counts()

Topic
1    13
0    13
2    10
3     8
4     6
Name: count, dtype: int64